name: Build Windows Executable

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if exist requirements.txt pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller GestorHorarios.spec --clean

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GestorHorarios-dist
          path: dist/ 