name: Build Windows Executable

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: List directory contents
        shell: pwsh
        run: |
          Get-ChildItem -Path . -Recurse | Select-Object FullName
          Write-Host "Current directory: $(Get-Location)"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Verify spec file
        shell: pwsh
        run: |
          if (-not (Test-Path GestorHorarios.spec)) {
            Write-Error "GestorHorarios.spec not found!"
            exit 1
          }
          Write-Host "GestorHorarios.spec found at: $(Resolve-Path GestorHorarios.spec)"

      - name: Build executable with PyInstaller
        shell: pwsh
        run: |
          pyinstaller GestorHorarios.spec --clean

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GestorHorarios-dist
          path: dist/ 